name: OnlineGUI
author: MrIvek
version: 1.6.1
main: com.craft0.mrivek.onlinegui.OnlineGUI
description: Display all online players in minecraft inventory.
softdepend: [Essentials, GroupManager]
api-version: 1.13
commands:
  online:
    usage: /online
    description: See who is online on the server.
    aliases: [players, list]